title: GUDEN
author: MrGametop1
email: kasperglud13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yderst spændene

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
